import '@egjs/react-flicking/dist/flicking.css';
import { Button, Card, CardHeader } from '@nextui-org/react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { Providers } from '../(home)/providers';
import '../globals.css';

interface Props {
	children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

function RootLayout({ children }: Props) {
	return (
		<html lang='en'>
			<body className={`${inter.className} min-h-screen dark text-foreground bg-background`}>
				<Providers>
					<div className='flex h-screen justify-center items-center'>
						<Card className='w-1/4 px-8 py-5'>
							<CardHeader className='px-0 justify-between'>
								<h1 className='font-bold text-2xl'>Movie App</h1>
								<Button variant='bordered'>Close</Button>
							</CardHeader>
							{children}
						</Card>
					</div>
				</Providers>
			</body>
		</html>
	);
}

export default RootLayout;
