import Footer from '@/components/Footer';
import NavBar from '@/components/NavBar';
import '@egjs/react-flicking/dist/flicking.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '../(home)/providers';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${inter.className} min-h-screen dark text-foreground bg-background`}>
				<Providers>
					<NavBar />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
